"""
Init Command - Initialize Perfwatch configuration.
"""

import os
from pathlib import Path
import typer
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel

app = typer.Typer(help="Initialize Perfwatch configuration")
console = Console()


@app.callback(invoke_without_command=True)
def init(
    ctx: typer.Context,
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing configuration"),
):
    """Initialize Perfwatch configuration and API keys."""
    
    console.print()
    console.print(Panel.fit(
        "[bold cyan]🔧 Perfwatch Initialization[/bold cyan]\n\n"
        "[dim]Setting up your configuration...[/dim]",
        border_style="cyan"
    ))
    console.print()
    
    # Determine config paths
    home_dir = Path.home()
    config_dir = home_dir / ".perfwatch"
    env_file = Path.cwd() / ".env"
    
    # Create config directory
    config_dir.mkdir(exist_ok=True)
    console.print(f"[green]✓[/green] Config directory: {config_dir}")
    
    # Check for existing .env
    if env_file.exists() and not force:
        if not Confirm.ask("[yellow]⚠[/yellow] .env file already exists. Overwrite?"):
            console.print("[dim]Keeping existing configuration.[/dim]")
            return
    
    # Get API keys
    console.print()
    console.print("[bold]API Configuration[/bold]")
    console.print("[dim]Press Enter to skip optional keys[/dim]")
    console.print()
    
    # Gemini API Key (required for AI features)
    gemini_key = Prompt.ask(
        "[cyan]Google Gemini API Key[/cyan] (required for AI)",
        password=True,
        default=""
    )
    
    # PageSpeed API Key (optional)
    pagespeed_key = Prompt.ask(
        "[cyan]PageSpeed Insights API Key[/cyan] (optional)",
        password=True,
        default=""
    )
    
    # Write .env file
    env_content = f"""# Perfwatch Configuration
# Generated by 'perfwatch init'

# Google Gemini API Key (required for AI features)
GOOGLE_API_KEY={gemini_key}

# Google PageSpeed Insights API Key (optional, increases rate limit)
PAGESPEED_API_KEY={pagespeed_key}

# Default settings
PERFWATCH_TIMEOUT=30
PERFWATCH_MAX_CONCURRENT=10
"""
    
    env_file.write_text(env_content)
    console.print()
    console.print(f"[green]✓[/green] Configuration saved to: {env_file}")
    
    # Create reports directory
    reports_dir = Path.cwd() / "reports"
    reports_dir.mkdir(exist_ok=True)
    console.print(f"[green]✓[/green] Reports directory: {reports_dir}")
    
    # Final message
    console.print()
    console.print(Panel.fit(
        "[bold green]✓ Initialization Complete![/bold green]\n\n"
        "[white]You can now run:[/white]\n"
        "  [cyan]perfwatch audit --url https://example.com[/cyan]\n"
        "  [cyan]perfwatch lighthouse --url https://example.com[/cyan]\n"
        "  [cyan]perfwatch loadtest --url https://example.com[/cyan]",
        border_style="green"
    ))
    console.print()
